### ISSUE TITLE
Prime Factors task by Nastya

### ISSUE THREAD

**Issue by silvermilk** [krrg97/vnfm#7]
Hello, this is my [solution](https://github.com/silvermilk/vnfm/tree/master/src/main/vnfm/kata/primefactors/anchu)
@krrg97 please review.

**Comment by rokr97** [comment]
Nastya, each "for-each" statement is a potential target to use Java 8's Stream API.
Could you please explain why you should/shouldn't use streams in your case? It is an optional question, as I accept your solution in general.

NB: I like that you named argument of your function 'num' instead of just 'n', which can trigger minor warning in https://www.codacy.com/app/krrg97/vnfm/pullRequests.

**Comment by silvermilk** [comment]
Hello @krrg97 ,
Actually, I tried to use java 8 stream API features here, but I faced several problems such as:
- stream API forEach is basically used to iterate through existing collection, and I don't have collection at the very begining, I create it at the end.
- I can use IntStream to create a range and iterate through it, but there is also a problem. I cannot use non-final fields in lambda expresions. "num" in my case should be changed in each iteration and should be used in lambda expression. 
- Also in my opinion such code will be hard to understand, I mean usage of IntStream  in this particular case.
